<h1>注册页面</h1>

<?php use Phalcon\Tag; ?>

{{ "<h1>Hello<h1>"|e }}
{{ "<h1>Hello<h1>"|escape }}
{{ "robots"|length }}


<?php echo Tag::form("signup/register"); ?>

 
<p>    
	<label for="name">Name</label>
    <?php echo Tag::textField("username") ?>
</p>

<p>    
	<label for="name">Password</label>
    <?php echo Tag::passwordField("password") ?>
</p>

<p> 
	<label for="email">E-Mail</label>
    <?php echo Tag::textField("email") ?>
</p>


<p>
    <?php echo Tag::submitButton("Register") ?>
</p>


</form>